### ISSUE TITLE
Actors in World Outliner not visible in Light Mode

### ISSUE THREAD

**Issue by cascade-interactive** [hugoattal/DarkerNodes#111]
![IMG_20210123_133245.jpg](https://user-images.githubusercontent.com/65467012/105578318-7e87f080-5d7f-11eb-88c7-2c9fa36a1925.jpg)

**Comment by TheHerobrine** [comment]
Hey @CascadeNP 😄 ! Thank you for your feedback, the light theme is still very much experimental and not ready to use, but I'll fix this 😉

cf https://github.com/TheHerobrine/DarkerNodes/issues/17

**Comment by CascadeNP** [comment]
Yeah, sure, I know it's still in Beta. Just wanted to point it out, if you didn't already noticed. Thanks a lot for this addon btw, it's awesome

**Comment by TheHerobrine** [comment]
Arg, I'm not sure it's possible in fact, seems to be hardcoded 😞...

If I can't change this, the light theme is pointless... I'll try to find a workaround...

Line 3838 of file `Editor/SceneOutliner/Private/SSceneOutliner.cpp`
![image](https://user-images.githubusercontent.com/4563971/105607997-983a2f80-5da1-11eb-8ac6-7cf98d40aa09.png)

This is for this text, but the actors may use the same kind of logic...
![image](https://user-images.githubusercontent.com/4563971/105608022-c455b080-5da1-11eb-85d6-7010f1aed442.png)

**Comment by CascadeNP** [comment]
you might otherwise just change the background color to something darker just for this tab. It might not even look that bad

**Comment by TheHerobrine** [comment]
@CascadeNP Hum, I'd prefer keeping it white, but that's a good idea! (if it doesn't affect too much the rest)

I think it's quite complex thought... I'll report this to 2.6 I think (there will be already a lot of new features in 2.5)

**Comment by TheHerobrine** [comment]
Unless you use actively the light theme?

**Comment by hugoattal** [comment]
This is fixed in 3.0

![image](https://user-images.githubusercontent.com/4563971/167027662-972ab931-d36b-4792-a68f-038a2a3e61d9.png)
