### ISSUE TITLE
Followup: Change font size of all text

### ISSUE THREAD

**Issue by hugoattal** [hugoattal/DarkerNodes#115]
I should find a solution to update ALL size font. This might require a big hack.
https://github.com/TheHerobrine/DarkerNodes/issues/106

**Comment by TheHerobrine** [comment]
Maybe not before 3.0...

**Comment by msanioura** [comment]
I hope this happens sometime soon :) I have 2 x 4K monitors and it teases that there is no way to increase font size of Content Browser. But thanks for a great plugin!

**Comment by hugoattal** [comment]
This is fixed in 3.0
