### ISSUE TITLE
It came back, yikes

### ISSUE THREAD

**Issue by stardast132** [hugoattal/DarkerNodes#136]
![image](https://user-images.githubusercontent.com/75868062/108758526-cf227300-7510-11eb-9707-cc52fe30aa32.png)

**Comment by TheHerobrine** [comment]
Well, same things as usual, go into your editor settings and click "Fix missing elements" 😕 cf https://github.com/TheHerobrine/DarkerNodes/wiki/FAQ#some-elements-are-invisible--search-box-are-glitchy-or-unreadable--im-having-a-visual-bug

I didn't find to detect when this happens to fire it automatically yet 😞

**Comment by stardast132** [comment]
ok

**Comment by hugoattal** [comment]
I think this will fix it consistently: https://github.com/hugoattal/DarkerNodes/issues/144
