### ISSUE TITLE
I love programming

### ISSUE THREAD

**Issue by stardast132** [hugoattal/DarkerNodes#138]
![image](https://user-images.githubusercontent.com/75868062/109558933-a44f9600-7a9f-11eb-8452-d72adbc35864.png)

**Comment by stardast132** [comment]
(Had to unable the plugin)

**Comment by TheHerobrine** [comment]
Looks like you get it quite often 😅... Is there something special happening with your project, like editor crash?
I really need to detect that automatically, but still have no clue how to do that 😞...

(In any case, same as usual "Fix missing elements" :3)

**Comment by stardast132** [comment]
I migrated stuff to another project and back, enabled opaque decals,nothing else that I know of

**Comment by hugoattal** [comment]
I think this will fix it consistently: https://github.com/hugoattal/DarkerNodes/issues/144
