### ISSUE TITLE
Transform input boxes partially keep their default border radiuses

### ISSUE THREAD

**Issue by Gliptal** [hugoattal/DarkerNodes#143]
![UE4Editor_ITZ4SgjgAr](https://user-images.githubusercontent.com/3907646/116379297-2b588a80-a813-11eb-8be0-1afc9e57d1ce.png)

Amazing work anyways, the editor finally looks like it's from this decade. I love this design style.

**Comment by hugoattal** [comment]
> String properties have narrower input boxes than other properties (this is the same in vanilla):

If I recall correctly, it was kind of hard-coded and impossible to change 😕 ...

> Transform input boxes keep their default border radiuses on the coordinate side.

Hum, I'll see if it's possible to update this!

> I'll add more to this list as I use DarkerNodes.

I'd prefer if you create a new issue if you have another suggestion, it helps keep things tidy 😅

> Amazing work anyways, the editor finally looks like it's from this decade. I love this design style.

Thank you very much, it means a lot ❤️ ! Don't hesitate to leave a review, it really helps 🙂 !

**Comment by Gliptal** [comment]
> I'd prefer if you create a new issue if you have another suggestion, it helps keep things tidy 😅

Sure, I'll update this issue to only refer to the transform input boxes then.
 
> Thank you very much, it means a lot ❤️ ! Don't hesitate to leave a review, it really helps 🙂 !

Done!

**Comment by hugoattal** [comment]
There's no more radius change for inputs in 3.0
