### ISSUE TITLE
Graphic problems

### ISSUE THREAD

**Issue by Midway83300** [hugoattal/DarkerNodes#147]
Hi ! 
I bought your 2 plugins since a few days and I have weird graphics problems.

First : when I have a dropdown menu like output variable for a function, I have this kind of bug :
![UE4Editor_nZTXNJ4uft](https://user-images.githubusercontent.com/6842033/116846748-582ce900-abe9-11eb-9aa7-399a3cac3422.png)

Second, and I'm not sure your plugin is the reason (I didn't really had Unreal Engine since a long time before) : 
After a long UE4 session, I have the same problem as this guy : https://answers.unrealengine.com/questions/1005720/view.html

Thanks in advance! 

( ps : I love Electronic Nodes :) )

**Comment by hugoattal** [comment]
@Midway83300 Hello, thank you very much for buying Electronic Nodes and Darker Nodes 🙂 !

I'm sorry you're experiencing this... The first problem comes from Darker Nodes, you can fix it like this:
https://github.com/hugoattal/DarkerNodes/wiki/FAQ#some-elements-are-invisible--search-box-are-glitchy-or-unreadable--im-having-a-visual-bug

I don't know about the second problem, but this solution might also fix it 🤔...

**Comment by Midway83300** [comment]
Thanks for the answer ! It's working now :)
Concerning my second problem, I'm goin' to investigate. I'm sure it's a problem not related to your plugin (I already had this problem with your plugin deactivated)
Thanks again !
