### ISSUE TITLE
Backround of Spline Generation Panel is black instead of set color.

### ISSUE THREAD

**Issue by cascade-interactive** [hugoattal/DarkerNodes#150]
![image](https://user-images.githubusercontent.com/65467012/118272364-ca8faa00-b4c2-11eb-86a0-17c0ad84dc55.png)

**Comment by CascadeNP** [comment]
Make a new actor, add a 'spline' component, left-click first on one of the two dots, right-click it then and click on Spline Generator.

Documentation: https://docs.unrealengine.com/en-US/BuildingWorlds/BlueprintSplines/HowTo/EditSplineComponentInEditor/index.html

**Comment by hugoattal** [comment]
Wow, I didn't know this existed 😮 !

In any case, I didn't manage to reproduce...
![image](https://user-images.githubusercontent.com/4563971/118371157-8a582680-b5ab-11eb-8ff9-b88f0896f154.png)

Could you check if a "Fix Missing Elements" (in Edit/Editor Preferences/Darker Nodes) fixes it? If not, could you give me your engine and plugin version?

**Comment by hugoattal** [comment]
Soooo... Did it work?

**Comment by CascadeNP** [comment]
Sorry for not getting back to you earlier. So unfortunately it did not work. I've already tried on multiple mashines and I had the same thing happening every time. My guess - after some thinkering with the settings - is, that it has something to do, with the color of the "Header Bar" (the top bar with window options, like minimize and close) - as I set it to pure black.

**Comment by hugoattal** [comment]
@CascadeNP Ok, I managed to reproduce! I'm on it!

**Comment by hugoattal** [comment]
Fix on V3 for UE5
