### ISSUE TITLE
Missing Icon > Datasmith

### ISSUE THREAD

**Issue by gnlkrmz** [hugoattal/DarkerNodes#151]
- Noticed Datasmith icon is missing when the plugin is enabled.

Thank you

<img width="698" alt="datasmith" src="https://user-images.githubusercontent.com/10071439/119571552-54166600-bd66-11eb-90f0-373cb5afdf52.PNG">

**Comment by hugoattal** [comment]
Rejected, there won't be icon update for UE5.
