### ISSUE TITLE
Text overlaps when Search function is used  in Detail Panel

### ISSUE THREAD

**Issue by gnlkrmz** [hugoattal/DarkerNodes#153]
When i try to use search function  in detail panel, all the text overlaps. I wonder if this problem can be re-created on your end to see if this issue is from darker nodes or something else.  ( I did try same thing with default theme and it did not happen)

![search_v01](https://user-images.githubusercontent.com/10071439/120125426-9debbb80-c16d-11eb-9d18-4d67bdb7ee51.gif)

**Comment by hugoattal** [comment]
Hello @gnlkrmz and sorry for the inconvenience... Could you try to follow those steps?
https://github.com/hugoattal/DarkerNodes/wiki/FAQ#some-elements-are-invisible--search-box-are-glitchy-or-unreadable--im-having-a-visual-bug

- Go to Edit/Editor Preferences/Plugins/Darker Nodes Plugin
- Click Fix Missing Elements (if the checkbox stay unchecked, it's normal)

Could you confirm if that solve the issue?

**Comment by gnlkrmz** [comment]
@hugoattal Thank you. It did fix !!
I'll keep this in mind.

![search_v03](https://user-images.githubusercontent.com/10071439/120127084-35074200-c173-11eb-9d06-ae8e48372ad1.gif)

**Comment by hugoattal** [comment]
Nice 😄 ! I'm closing the issue!

**Comment by gnlkrmz** [comment]
Hi @hugoattal 
I got in to same problem again. I did try "fix missing elements" and i did uninstall and re install the plugin. But no luck :(im not sure why its happening. 


![search_v03](https://user-images.githubusercontent.com/10071439/120427228-63794e80-c326-11eb-9c1e-e9f376fe97d4.gif)


<img width="958" alt="Capturead" src="https://user-images.githubusercontent.com/10071439/120427244-6a07c600-c326-11eb-8eff-73dc62646bb0.PNG">

**Comment by hugoattal** [comment]
Hum, that's weird, even in the settings, you're missing elements like input (which should be invisible)...

- Could you tell me what version of the Engine and Darker Nodes you have?
- Do you have a BP based or a C++ based project?
- Could you try to copy/paste the plugin inside your project plugins folder and tell me if that change anything?
- Would you be available on discord to debug this?

**Comment by gnlkrmz** [comment]
1) UE: 4.26.2
     DN: 4.26.0

2) I do have BP based projects. 
But i tried screen captures in my previous posting with a fresh scene without any content or files. It was an empty project with only engine content. Problem sometimes goes away sometimes comes back. its very random. 

3) Plugin is installed in UE4 engine folder > C:\Program Files\Epic Games\UE_4.26\Engine\Plugins\Marketplace  
I did copy / paste but no change.

4) Sure i can be. Let me install discord. Can you let me know how i find you in discord ?

Thanks,

**Comment by hugoattal** [comment]
Darker Nods should be version 2.6, you can see it in Edit/Plugins in the top right corner of Darker Nodes.
![image](https://user-images.githubusercontent.com/4563971/120567867-fdb6c080-c412-11eb-939f-9d4a6c67e06c.png)

In any case, I'm deeply sorry for the inconvenience... You should be able to add me on discord with my ID `Herobrine#6480`.

**Comment by gnlkrmz** [comment]
no worries at all. 
I'll add you via discord
and Im including the version capture

<img width="622" alt="Capture" src="https://user-images.githubusercontent.com/10071439/120568097-1352c880-c3c8-11eb-8792-c5f71b1c1ac5.PNG">

**Comment by hugoattal** [comment]
I'm closing this, feel free to re-open if you still have the problem in 3.0
