### ISSUE TITLE
Modules missing | Linux Editor

### ISSUE THREAD

**Issue by Proton64** [hugoattal/DarkerNodes#156]
I purchased the plugins and then downloaded them through the heroic launcher (a way to download marketplace assets on Linux). After that, I put them in the Engine Plugins folder as it should be and enabled them to always load in every Project. When loading a project, Unreal Engine fails to load the Plugins and gives me the following message:
![image](https://user-images.githubusercontent.com/42376598/129578342-dfa7df26-1354-487b-b5d5-9ff882290f98.png)

**Does anyone know how to fix this?**

**Comment by hugoattal** [comment]
Hey! Well, you need to compile the plugins. To do this, you'll just have to put them into the `Plugins` folder of one of your projects (create it if it does not exist).
Then, make sure that your project is C++ based (if it's BP based, just create a random class in your project, then delete it).
Once done, you'll just have to open your project and it should compile it automatically.

**Comment by hugoattal** [comment]
Here is a little tutorial: https://github.com/hugoattal/ElectronicNodes/wiki/How-to-install-Electronic-Nodes-on-previous-version-of-the-engine%3F-On-custom-build%3F

**Comment by Proton64** [comment]
I'll try that out 👍

**Comment by hugoattal** [comment]
Hum, you need to close the engine, and they should compile during the startup phase.
You can also delete the folders "Binaries" and "Intermediate" inside the plugin folder.
If this does not work, I suggest you try building them from an IDE...

If nothing work, would be available for a quick screen sharing on discord?

**Comment by Proton64** [comment]
Hey,
I did delete the "Binaries" and "Intermediate" folders inside both of the plugins.
Since there was no log dialouge, I simply started the Editor in a terminal to get more info as to why it does not want to compile. Seems like Unreal has problems to compile the plugin because it would modify core engine modules and plugins.
Gist: https://gist.github.com/Proton64/8312a6b0cd87ab0eed7d994cd47c231f

**Comment by hugoattal** [comment]
Hum, seems like the `Building would modify the following engine files` is a common building issue on Linux...

I found these:

https://forums.unrealengine.com/t/solved-upgrade-c-project-from-ue-4-24-to-4-25-under-linux/144950/2
Says to add `DefaultBuildSettings = BuildSettingsVersion.V2;` to both `.Target.cs` of your project
(this should work with the startup build)

https://community.gamedev.tv/t/unable-to-run-bull-and-cow-game-on-linux-ubuntu/155138/3
Kind of a step by step solution
(this imply a build with VSCode)

Tell me if you need any help with these.

**Comment by Proton64** [comment]
Hey,
I already found the first suggestion, these lines were already in the [...].Target.cs file in my project.
I just did the second suggestion and compiled a Development Build.
Trying to launch the project **still** results in the recompilation dialogue and the same error message.

**Comment by hugoattal** [comment]
> I just did the second suggestion and compiled a Development Build.
Trying to launch the project still results in the recompilation dialogue and the same error message.

Wait, so it compiled successfully (including the plugins), but fail to launch? Seems a bit weird to me 🤔 ...
Could you check that after deleting the "Binaries" and "Intermediate" folders, and building it, they're back?

**Comment by Proton64** [comment]
Only the Intermediate folders are back. The second suggestion compiled the project as a development build, it seems like it did not compile the plugins.

**Comment by hugoattal** [comment]
Arg, seems like it's not the solution then... I just came accross this video: https://youtu.be/WtfLfYY_k2Y?t=346

Here are the written down instructions if you prefer
- Go into your engine folder, then Engine/Build/BatchFiles
- Open a terminal here
- Type `./RunUAT.sh BuildPlugin -Plugin="{your-path-to-the-.uplugin-file}"` -Package="{path-to-the-build-folder-you-want}"

And this should (hopefully) create the Binaries folder for you!

**Comment by Proton64** [comment]
![image](https://user-images.githubusercontent.com/42376598/129595741-17801951-8232-47c9-aff8-21655655e838.png)
**It works now!**
Finally, my god. Why does it have to be so complicated.

**Comment by hugoattal** [comment]
Niiiice 😄 ! (and sorry for the complicated process 😕 ...)

**Comment by Proton64** [comment]
Aye, that's on Epig being so clever to make this complicated, not you.
