### ISSUE TITLE
UE Appearance Colors don't seem to work

### ISSUE THREAD

**Issue by JinVeiss** [hugoattal/DarkerNodes#157]
UE 4.27
Latest Darker Nodes

I can change them with Darker Nodes disabled, but if I then enable it they revert to a dark orange and brown color.

<img width="580" alt="UE4Editor_OWRkdeQhS4" src="https://user-images.githubusercontent.com/26267774/132167993-1d7c7024-84fc-4b0b-8aac-dff39240d45b.png">
General-Appearance-Colors:
Selection Color
Pressed Selection Color
Inactive Selection Color

I've restarted the editor after changing them and tried the Fix Missing Elements option.

**Comment by hugoattal** [comment]
Hello @JinVeiss !

Well, Darker Nodes override some colors of the engine, but everything is customizable in the settings (under Edit/Editor Preferences/Darker Nodes)

Simple solution: you can change your theme color here:
![image](https://user-images.githubusercontent.com/4563971/132182774-a2207e1a-2314-4257-89cb-8d72da111e6c.png)

Other solution: you can change almost anything under Customization (still in the Editor Preferences/Darker Nodes window)
You want to tick "Use Color Customization" and change the "Custom Primary Color"

Please note that changing the selection color require TWO restarts of the engine to work (yeah, I know... but you only have to do this once 😅!)

**Comment by JinVeiss** [comment]
The Darker Nodes colors in the preferences seem to work, but I can't find the colors referenced in the general appearance settings there to change that brown color and the dark orange ones. Are you able to get rid of that brown?

**Comment by hugoattal** [comment]
I'm sorry, I'm not quite sure on what color you're talking about... Could you please take a screen of it?

Also, keep in mind that the theme temperature can affect colors
![image](https://user-images.githubusercontent.com/4563971/132424804-83e66d5e-961b-476c-9329-0aa42b19edfb.png)
(Cool is blueish, warm is yellowish)

**Comment by JinVeiss** [comment]
The brown color in your screenshot there, looks the same as mine or a little lighter. It's the same color listed for inactive selection color in appearance. The selection color and pressed selection color from my first screenshot also aren't changeable. They show around the viewport and on the side of certain items like the selected actor classes as well as the buttons in the top right of the viewport usually. I noticed the highlights behind those buttons in the top (move, scale, rotate, snaps, etc.) aren't changing when selected like usual.
<img width="59" alt="UE4Editor_YDEdxXpEdz" src="https://user-images.githubusercontent.com/26267774/132427788-981473e7-06b0-482d-bf21-2cef4bf47428.png">
<img width="136" alt="UE4Editor_aTOBpAvfQg" src="https://user-images.githubusercontent.com/26267774/132427794-53e6f98d-c169-4f91-82b0-fc24064fa14c.png">
<img width="299" alt="UE4Editor_rJMbowjMJd" src="https://user-images.githubusercontent.com/26267774/132427798-7831ad10-a381-415c-b8a5-e07ba0ca4b36.png">

**Comment by hugoattal** [comment]
Well, let's say I change the Primary color to cyan:
![image](https://user-images.githubusercontent.com/4563971/132472028-bb917c68-64f9-4df8-a692-dd0cb8b1e073.png)

It basically changes the primary color to a predefined one (make sure that you do not let the "Use Color Customization" option checked if you use the "Primary Color" option)
![image](https://user-images.githubusercontent.com/4563971/132472109-395d6c32-8b87-4370-9f15-d35402a4ad5a.png)

After restarting the engine **twice** (if you want, you can set up a shortcut for restating your engine in General / Keyboard shortcuts, like Ctrl+Shift+R), it should now be cyan everywhere:
![image](https://user-images.githubusercontent.com/4563971/132472483-dacab4ae-c0cc-4727-9cc4-6c9de89966c8.png)
![image](https://user-images.githubusercontent.com/4563971/132472505-0d5461ed-4567-47dc-9e4d-b2d4efb5dd21.png)
![image](https://user-images.githubusercontent.com/4563971/132472528-731c7bc1-fadb-431e-84e3-f1d76d2c57d0.png)

Btw, if you have invisible background behind your top buttons like in your screenshot, you want to check "Fix Missing Elements" in the top of the plugin settings to recompile those.

**Comment by hugoattal** [comment]
If this does not work, could you please tell me the version of your engine and the version of the plugin?
