### ISSUE TITLE
Bought the Plugin some months ago, now I have to buy it again!?!?!?!

### ISSUE THREAD

**Issue by stardast132** [hugoattal/DarkerNodes#159]
I haven't changed my account, I don't understand why now I have to buy it again. It makes no sense

**Comment by hugoattal** [comment]
You absolutely don't need to buy it again. Once you buy it, you keep it. It's most likely an Epic Games Launcher bug, and I suggest you contact the marketplace team by mail or on the official forum.

**Comment by stardast132** [comment]
Fortunately I had it installed so I transfered the folder to my other pc, it worked
