### ISSUE TITLE
Behaviour tree node highlight slight misalign

### ISSUE THREAD

**Issue by Getue** [hugoattal/DarkerNodes#162]
![image](https://user-images.githubusercontent.com/76600194/150660229-1bb0d7aa-2015-445b-9ed8-cc83c64aa8a9.png)

Top Left: Darker Nodes - Extend Nodes disabled
Top Right: Darker Nodes plugin disabled
Bottom: Darker Nodes - Extend Nodes enabled

**Comment by hugoattal** [comment]
Fixed for 3.1!

![image](https://user-images.githubusercontent.com/4563971/167026552-f4f89779-bed8-4163-81f9-5bd776a8cc52.png)
