### ISSUE TITLE
Request: Option to hide Marketplace Icon 

### ISSUE THREAD

**Issue by TheBanishingOfMosquito** [hugoattal/DarkerNodes#163]
![DefaultMarketplaceIcon](https://user-images.githubusercontent.com/65665572/154118989-1466ace1-3155-42ce-99c0-16e1f93795bd.png)
![NoMarketplaceIcon](https://user-images.githubusercontent.com/65665572/154118997-40a71757-5d4b-408b-b766-efaaaab3abfe.png)

Can you hide this button pls. Just using the color of the toolbar as a plane top to hide the name and symbol would be fine. Even if its clickable. Actually this button doesnt work anyway.

I think we dont need this button. Its taking visuall space away. And the symbol is too strong. Feels like we are in a shopping maul. If I am in supermarket I always try to get out asap. 

IMHO the levelviewport should not be to place to be constantly reminded that we can go to the marketplace and buy stuff. Its kind of an advertisment. Would be great if we can block it. (see image above)

**Comment by TheBanishingOfMosquito** [comment]
Is it possible to make a new Icon that is just a square with black color or the color that is using the toolbar color background. And for the Icon name, changeing the font color to the same picked color.

Visually it does the thing. And this would work right?
![Doable](https://user-images.githubusercontent.com/65665572/154135869-c767e19f-5baa-42e7-bf78-c8b5772858a5.png)

**Comment by hugoattal** [comment]
> In my case, even if I click nothing happens. It seems to be the case for many users.

I'm afraid this has nothing to do with Darker Nodes, it's just on the "vanilla" engine...

> changing the font color to the same picked color

Well, this is not possible... To simplify a bit, there's many "model" of fonts generated by the engine, and I can only modify the color of some of them. To be fair, I can modify this model, but all the texts based on this model will be affected, meaning all the text of the toolbar (and possibly more) will be invisible.

**Comment by TheBanishingOfMosquito** [comment]
Too bad that Epic doesnt let us change it by default.  There is one more thing>
![image](https://user-images.githubusercontent.com/65665572/154256298-5e4d4648-72a1-40ce-a5c0-f5087a203eb9.png)
![image](https://user-images.githubusercontent.com/65665572/154256767-7e815042-b04c-4939-9a78-1a19c8bd9f98.png)

If the toolbar is in small mode. There is no text! So in other words. If you include the _alpha option_ that you suggested . We can hide it as loong as we use the ''Use Small Tool Bar Icons'' behaviour. What do you think. I would say most of us use small icons for screen space reasons in the first place. If there is a checkbox for this turned off by default. As Experimental. This would be great.

**Comment by hugoattal** [comment]
Well why not then. I'll add a checkbox "Hide Marketplace icon" for the next version.

**Comment by TheBanishingOfMosquito** [comment]
Awsome, will be grateful!✨

**Comment by hugoattal** [comment]
Rejected for version 3 (Sorry, I'm focusing on UE5 compatibility and new features... 😕)

One solution for you could be to delete the icon from the plugin folder located in
`D:\Program Files\Epic Games\UE_4.27\Engine\Plugins\Marketplace\DarkerNodes\Resources\Theme\Menu\Line`
