### ISSUE TITLE
Fix Missing Elements not work

### ISSUE THREAD

**Issue by dongcoco596** [hugoattal/DarkerNodes#177]
I still got a visual bug. 
From Last Question under UEMarkerplace - Darker Nodes.
[Engine Version 4.27.2 / Plugin Version 2.6]
I found these errors in output log:

LogShaderCompilers: Warning: Failed to compile Material /DarkerNodes/Materials/ButtonCut.ButtonCut for platform PCD3D_SM5, Default Material will be used in game.
LogShaderCompilers: Display: Can't map virtual shader source path "/DarkerNodes/ButtonCut.usf".
LogShaderCompilers: Display: /Engine/Generated/Material.ush(2082): error: Can't open include file "/DarkerNodes/ButtonCut.usf"
    #include "/DarkerNodes/ButtonCut.usf"
    from /Engine/Private/SlateShaderCommon.ush: 4:    #include "/Engine/Generated/Material.ush"
    from /Engine/Private/SlateElementPixelShader.usf: 6:    #include "SlateShaderCommon.ush"
LogShaderCompilers: Display: 1 err0r in preprocessor.
LogShaderCompilers: Display: /Engine/Generated/Material.ush(2082): error: Can't open include file "/DarkerNodes/ButtonCut.usf"
    #include "/DarkerNodes/ButtonCut.usf"
    from /Engine/Private/SlateShaderCommon.ush: 4:    #include "/Engine/Generated/Material.ush"
    from /Engine/Private/SlateVertexShader.usf: 5:    #include "SlateShaderCommon.ush"
LogShaderCompilers: Display: /Engine/Generated/Material.ush(2082): error: Can't open include file "/DarkerNodes/ButtonCut.usf"
    #include "/DarkerNodes/ButtonCut.usf"
    from /Engine/Private/BasePassVertexCommon.ush: 15:    #include "/Engine/Generated/Material.ush"
    from /Engine/Private/BasePassVertexShader.usf: 7:    #include "BasePassVertexCommon.ush"
    
    Could it be helpful?

**Comment by hugoattal** [comment]
Hum, that's pretty weird, it seems like it's missing some files... Could you try to uninstall and reinstall Darker Nodes?

Make sure that the `Epic Games\UE_4.27\Engine\Plugins\Marketplace\DarkerNodes` folder does not exist anymore before reinstalling it.

**Comment by dongcoco596** [comment]
> Hum, that's pretty weird, it seems like it's missing some files... Could you try to uninstall and reinstall Darker Nodes?
> 
> Make sure that the `Epic Games\UE_4.27\Engine\Plugins\Marketplace\DarkerNodes` folder does not exist anymore before reinstalling it.

I tried, that logged error seems not to be root cause because it shows again after a reinstallation but this time everything looks fine.

However, after reopening the project several times, the visual bug comes again which cannot be fixed by Fix Missing Element

**Comment by dongcoco596** [comment]
> Hum, that's pretty weird, it seems like it's missing some files... Could you try to uninstall and reinstall Darker Nodes?
> 
> Make sure that the `Epic Games\UE_4.27\Engine\Plugins\Marketplace\DarkerNodes` folder does not exist anymore before reinstalling it.

I did a lot and finally found the issue. It seems to be caused by unusual custom layout. In more details, if the game scene viewport is folded and hiden when the project opens, other part of the editor will be flickering and fuzzy.

I am not a native English speaker and I am afraid that some statements may be misleading. So I paste a screenshot.  

![搜狗截图20230421083052](https://user-images.githubusercontent.com/104130287/233515184-c6116b73-5105-4a8b-baff-546a111086c0.png)

**Comment by dongcoco596** [comment]
simply clicking and switching to view port will tackle the problem. I wonder why ...

**Comment by hugoattal** [comment]
> if the game scene viewport is folded and hiden when the project opens, other part of the editor will be flickering and fuzzy. [...] simply clicking and switching to view port will tackle the problem. I wonder why ...

Wow, good finding, thanks a lot! The Unreal Engine can be super weird sometimes... Anyway, happy that you found the solution, I may add this to the FAQ in case someone has the same problem 🙂
