### ISSUE TITLE
The asset 'XX/Box' (and others) failed to save

### ISSUE THREAD

**Issue by vekien** [hugoattal/DarkerNodes#179]
Hello,

Installed this on a new 5.2 project and I keep getting these errors whenever I do changes to the plugins settings. Clicking "fix" doesn't fix it either.

Several popups happen saying "The asset 'X' failed to save", it is always the same 4.

![image](https://github.com/hugoattal/DarkerNodes/assets/270800/d8911794-2ad1-434a-b36f-aca2f78f9673)

![image](https://github.com/hugoattal/DarkerNodes/assets/270800/9afed207-81ab-41f9-a3e0-c1d03c0f27ba)

Any clues what might cause this? Tried re-installing.

**Comment by hugoattal** [comment]
Hum, that's weird... I'm looking into it...

**Comment by vekien** [comment]
I tried another project, and when I click "Fix missing elements" (even if i dont click this but change like font, or colour, etc) it happened again. So it isn't project specific.

![image](https://github.com/hugoattal/DarkerNodes/assets/270800/9e17d89c-2fb8-47ac-b886-ad4253dbbdeb)

**Comment by hugoattal** [comment]
I'm sorry, but I didn't manage to reproduce the bug, event on a clean new projet...

I suggest a fresh install of Darker Nodes:
- Uninstall Darker Nodes
- Close the Epic Games Launcher
- Delete the `C:\Program Files\Epic Games\UE_5.2\Engine\Plugins\Marketplace\DarkerNodes` folder
(Remove the plugin for the /Plugins folder of your project if it is present)
- Restart the Epic Games Launcher
- Reinstall Darker Nodes

Could you please try this and tell me if that fixes your bug?

**Comment by vekien** [comment]
Hey @hugoattal 

That fixed it :) thank you so much!
