### ISSUE TITLE
Trying to compile game in UE5.2.1 and getting compile errors because of Darker Nodes

### ISSUE THREAD

**Issue by SavannahGames** [hugoattal/DarkerNodes#184]
Error log: https://pastebin.com/9QUjP0wp
Please advise.
Happens in Development & Shipping packaging

**Comment by hugoattal** [comment]
Hello, sorry for this... Are you packaging your game in a special way? Does it fail when packaging an empty project for example? Could you send me a minimum reproduction? That would be super helpful!

In the meantime, I'd suggest you disable Darker Nodes before packaging 😕

**Comment by SavannahGames** [comment]
> Hello, sorry for this... Are you packaging your game in a special way? Does it fail when packaging an empty project for example? Could you send me a minimum reproduction? That would be super helpful!
> 
> In the meantime, I'd suggest you disable Darker Nodes before packaging 😕

Hi I packaged the project using UE5.2.1 default thirdperson template with Blueprint functionality, there were no issues :/
The list of plugins goes as follows: 
1.) Advanced Main Menu & UI System by LazerTale
2.) Ascent Combat Framework
3.) AutoSizeComments
4.) ElectronicNodes
5.) LogicDriver

Maybe it is one of these plugins conflicting? I will try to debug, but just letting you know what the plugins are so far.
I will keep you updated if I find out the problem.

**Comment by SavannahGames** [comment]
Updating: Issue was resolved, but not sure how exactly.

**Comment by hugoattal** [comment]
Sometimes, Unreal does weird stuff ^^'... Happy that it solved itself!
