### ISSUE TITLE
Cook Failure

### ISSUE THREAD

**Issue by NicolasPanda** [hugoattal/DarkerNodes#187]
Hi,
When I do a build/Package Project, I have to disable Darker Node every time. Otherwise, I get this error, and the build fails every time.

```
Error: Can't map virtual shader source path "/DarkerNodes/CenterUVs.usf"
Error: Can't map virtual shader source path "/DarkerNodes/Panel.usf"
Error: Can't map virtual shader source path "/DarkerNodes/HeaderBox.usf"
Error: Can't map virtual shader source path "/DarkerNodes/ButtonCut.usf"
Error: Can't map virtual shader source path "/DarkerNodes/Button.usf"
Error: Can't map virtual shader source path "/DarkerNodes/Box.usf"
Packaging (Windows): BUILD FAILED
Error: Unknown Cook Failure
```

Version 5.4
Plugin version 3.4

**Comment by hugoattal** [comment]
Hello, and sorry for this...

I managed to reproduce the problem, I'm working on it!

**Comment by hugoattal** [comment]
Seems like a bug introduced in the Unreal Engine v5.4...

To fix it, I'll have to set the plugin `type` to `Editor` (where it should be `EditorNoCommandlet`).

If hope it does not affect a lot of people, the fix will be shipped in the next version, available in a couple of days!

**Comment by NicolasPanda** [comment]
No problem! Thank you for replying soo fast.
You're the best. Thanks
