### ISSUE TITLE
Update 5.4

### ISSUE THREAD

**Issue by pierresigwalt** [hugoattal/DarkerNodes#188]
Hi,

I am not sure it's an issue with the plugin but any helps is welcome.

I have update it to 5.4 and when opening a new Blueprint I am getting the following error for DarkerNode

**Something went wrong.  We were unable to verify your access to the plugin before timing out.**

![Screenshot 2024-05-19 090423](https://github.com/hugoattal/DarkerNodes/assets/8101858/61a7aee0-8982-4822-bb35-86537b7b790e)
![Screenshot 2024-05-19 090836](https://github.com/hugoattal/DarkerNodes/assets/8101858/97668a92-b2c7-4827-acb8-b6ead20b0e33)

Thank you for the time and help! (it's only happening with Darker Node and electronic node

**Comment by hugoattal** [comment]
Hey, it's likely only happening in Electronic Nodes, as I did not add this to Darker Nodes...

Though, it has been a mistake of my side, and this will be gone in the next version: https://github.com/hugoattal/ElectronicNodes/issues/89

In the meantime, you can disable it in Edit/Editor Preferences/Plugin/Electronic Nodes/Debug/Disable Entitlement Check
