### ISSUE TITLE
Ability to change th unfocused selection color

### ISSUE THREAD

**Issue by zjrl** [hugoattal/DarkerNodes#44]
Will there be Settings for that in the future?
![A3](https://user-images.githubusercontent.com/69996552/102949953-7a5c7f00-4504-11eb-80b4-f0f233c52954.jpg)

**Comment by TheHerobrine** [comment]
So, the buttons/textfields are very tricky to change as they are images. For now, I just created a bunch of style for those (resulting in hundreds of images).

I have a solution to be able to customize it, but that will be for the 2.0 as it's a pretty complicated one (in February probably)

For the selected unfocused color, I'll see if it's possible to change it 😉

**Comment by TheHerobrine** [comment]
I'm searching for the unfocused color, I looked into
- `Editor/WorldBrowser/Private/SWorldHierarchyImpl.cpp`
- `Editor/WorldBrowser/Private/SWorldHierarchyItem.cpp`
- `Editor/WorldBrowser/Private/SLevelsTreeWidget.cpp`
- `Runtime/Slate/Public/Widgets/Views/STreeView.h`

but I couldn't put my hands on it yet... I'll look again for the 1.7 or 2.0 😕

**Comment by TheHerobrine** [comment]
All the buttons and textfields are now customizable on 2.0 😄 ! (It's pending approval, so not available yet, but probably in the next 24h 😉)

**Comment by TheHerobrine** [comment]
Well, I'll keep this issue for the selected unfocus color. All other things are on this issue: https://github.com/TheHerobrine/DarkerNodes/issues/66

**Comment by hugoattal** [comment]
This is fixed in 3.0
